function H_x = duocopterCostate(in1,in2,u1_sym,u2_sym,g_syms,m1_syms,m2_syms,d_syms)
%duocopterCostate
%    H_x = duocopterCostate(IN1,IN2,U1_SYM,U2_SYM,G_SYMS,M1_SYMS,M2_SYMS,D_SYMS)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    16-Apr-2025 22:38:00

lambda_sym1 = in2(1,:);
lambda_sym2 = in2(2,:);
lambda_sym3 = in2(3,:);
lambda_sym4 = in2(4,:);
lambda_sym5 = in2(5,:);
x3 = in1(3,:);
t2 = m1_syms+m2_syms;
t3 = u1_sym+u2_sym;
t4 = 1.0./t2;
H_x = [0.0;0.0;lambda_sym4.*t3.*t4.*cos(x3)+lambda_sym5.*t3.*t4.*sin(x3);-lambda_sym1;-lambda_sym2;-lambda_sym3];
end
