function u = optimalU(d,lambda_sym4,lambda_sym5,lambda_sym6,m1,m2,x3)
%optimalU
%    [OUT1,OUT2] = optimalU(D,LAMBDA_SYM4,LAMBDA_SYM5,LAMBDA_SYM6,M1,M2,X3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-Apr-2025 22:17:36

t2 = cos(x3);
t3 = sin(x3);
t4 = m1+m2;
t5 = 1.0./d;
t6 = 1.0./t4;
t7 = lambda_sym5.*t2.*t6;
t8 = lambda_sym4.*t3.*t6;
t9 = -t7;
out1 = t8+t9-(lambda_sym6.*t5)./m1;
out2 = t8+t9+(lambda_sym6.*t5)./m2;


u = [out1; out2];
end
